FOGL-526: added 'jq' for JSON parsing
FOGL-526: added 'jq' for JSON parsing

diff --git a/scripts/tasks/update b/scripts/tasks/update
--- a/scripts/tasks/update
+++ b/scripts/tasks/update
@@ -93,16 +93,21 @@ write_log "FogLAMP[${$}]" "info" "${TASK_NAME} $0: FogLAMP API URL is [${REST_AP
 API_OUTPUT=`curl -s -k --max-time 20 -d "${JSON_CATEGORY_PAYLOAD}" -X POST "${REST_API_URL}/foglamp/category" | tr -d ' '`
 
 # Verify we have created or the category exists
-RET=`echo $API_OUTPUT | grep -o "\"key\":\"${PACKAGE_UPDATE_KEY}\""`
-MATCH_VAL="\"key\":\"${PACKAGE_UPDATE_KEY}\""
-if [ "${RET}" != "${MATCH_VAL}" ]; then
+RET=`echo $API_OUTPUT | jq '.key' | tr -d '"'`
+if [ "${RET}" != "${PACKAGE_UPDATE_KEY}" ]; then
 	write_log "FogLAMP[${$}]" "err" "${TASK_NAME} $0: error checking/creating configuration via REST API [${API_OUTPUT}]" "all" "pretty"
 	exit 1
 fi
 
 # Get 'repository' value from JSON
-REPO_URL=`echo ${API_OUTPUT} | grep -o '"repository":{.*"value":".*"' | grep -o '"value":".*",' | awk -F',' '{print $1}' | awk -F '"value":' '{print $2}' | tr -d '"}'`
-
+REPO_URL=`echo ${API_OUTPUT} | jq '.value.repository.value' | tr -d '"'`
+if [ ! "${REPO_URL}" ] || [ "${REPO_URL}" = "null" ]; then
+	REPO_URL=`echo ${API_OUTPUT} | jq '.value.repository.default' | tr -d '"'`
+	if [ ! "${REPO_URL}" ] || [ "${REPO_URL}" = "null" ]; then
+    		write_log "FogLAMP[${$}]" "err" "${TASK_NAME} $0: cannot get package repository: [${REPO_URL}]" "all" "pretty"
+		exit 3
+	fi
+fi
 write_log "FogLAMP[${$}]" "info" "${TASK_NAME} $0: Update repository [${REPO_URL}], package type [Snap]" "all" "pretty"
 
 #
